// Internationalization configuration and translations

export type Locale = 'en' | 'ja';

export const defaultLocale: Locale = 'en';

// Translation keys for the home page
export const translations = {
  en: {
    metadata: {
      title: 'Create Next App',
      description: 'Generated by create next app',
    },
    home: {
      title: 'To get started, edit the page.tsx file.',
      description: 'Looking for a starting point or more instructions? Head over to',
      templates: 'Templates',
      learning: 'Learning',
      center: 'center.',
      deployNow: 'Deploy Now',
      documentation: 'Documentation',
      nextJsLogo: 'Next.js logo',
      vercelLogomark: 'Vercel logomark',
    },
  },
  ja: {
    metadata: {
      title: 'Next Appを作成',
      description: 'create next appで生成されました',
    },
    home: {
      title: '開始するには、page.tsxファイルを編集してください。',
      description: '開始点や詳細な手順をお探しですか？こちらをご覧ください',
      templates: 'テンプレート',
      learning: '学習',
      center: 'センター。',
      deployNow: '今すぐデプロイ',
      documentation: 'ドキュメント',
      nextJsLogo: 'Next.jsロゴ',
      vercelLogomark: 'Vercelロゴマーク',
    },
  },
} as const;

// Helper function to get translations for a specific locale
export function getTranslations(locale: Locale = defaultLocale) {
  return translations[locale];
}
